name: mobile
description: Tuale app for mobile

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+14

environment:
  sdk: ">=2.15.0-285.0.dev <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.0
  flutter_signin_button: ^2.0.0
  page_transition: ^2.0.4
  email_auth: ^1.0.0
  dio: ^4.0.4
  flutter_spinkit: ^5.1.0
  twilio_phone_verify: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.11
  intl: ^0.17.0
  font_awesome_flutter: ^9.2.0
  scrollable_positioned_list: ^0.2.3
  file_picker: ^4.3.3
  camera: ^0.9.4+9
  photo_manager: ^1.3.10
  video_player: ^2.2.19
  provider: ^6.0.2
  numeric_keyboard: ^1.1.0
  flutter_screenutil: ^5.1.1
  flutter_paystack: ^1.0.5+1
  get: ^4.6.1
  image_picker: ^0.8.4+9
  chewie: ^1.3.0
  cloudinary_public: ^0.11.0
  flutter_overlay_loader: ^1.0.3
  percent_indicator: ^4.0.0
  http: ^0.13.4
  custom_pop_up_menu: ^1.2.3+1
  share_plus: ^4.0.1
  video_compress: ^3.1.0
  mixpanel_flutter: ^1.4.5
  new_version: ^0.3.0
  url_launcher: ^6.0.18
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  firebase_phone_auth_handler: ^1.0.3
  intl_phone_field: ^3.1.0
  easy_container: ^1.0.3
  pinput: ^2.2.7
  country_picker: ^2.0.15

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tuale_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/icon/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Medium.ttf
          weight: 500

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400


    - family: TualeIcons
      fonts:
        - asset: assets/fonts/TualeIcons.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #    fonts:
  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #           style: italic
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
