/// Flutter icons TualeIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TualeIcons
///      fonts:
///       - asset: fonts/TualeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TualeIcons {
  TualeIcons._();

  static const _kFontFam = 'TualeIcons';
  static const String? _kFontPkg = null;

  static const IconData tuale = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibing = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allposts = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData elipsis = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tualeactive = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usericon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData starredpost = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vibinguser = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notificationbell = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
